Repository Amsterdam/data-verkenner, pull requests merged in 2020-06, with the labels that each got.

#2717 Add 'Type' field to parkeervak detail
  src/map/components/detail-result/MapDetailResultItemTable.tsx
  src/map/services/map-services.config.ts
  src/map/services/normalize/normalize.js
  src/map/services/normalize/normalize.test.js
Labels: enhancement

#2739 Add missing GeoSearch calls for several map layers
  src/detail/services/glossary.constant.js
  src/map/services/map-search/category-labels-by-type.js
  src/map/services/map-search/category-labels.js
  src/map/services/map-search/map-search.js
  src/map/services/map-search/map-search.test.js
Labels: enhancement

#2755 Run single modern build in development mode
  webpack.common.ts
  webpack.dev.ts
Labels: enhancement

#2762 Remove GeoSearch calls that are already included in other resources
  src/map/services/map-search/map-search.js
  src/map/services/map-search/map-search.test.js
Labels: bug

#2764 Fix explosive dates and handle dates in detail panel
  modules/detail/components/detail/templates/explosieven/inslagen.html
  src/map/components/detail-result/MapDetailResultItem.tsx
  src/map/services/map-services.config.ts
  src/map/services/normalize/normalize.js
  src/map/services/normalize/normalize.test.js
  src/map/types/details.ts
Labels: bug, enhancement

#2765 Add missing themeColor to svgFill calls
  src/app/components/ActionButton/ActionButton.jsx
  src/app/components/HomePage/NavigationCard.jsx
  src/app/components/Links/LoginLink/LoginLinkContainer.jsx
  src/app/components/Links/SearchLink/SearchLink.jsx
Labels: bug

#2770 Read NODE_ENV from build environment
  Dockerfile
  Jenkinsfile
  docker-compose.yml
Labels: enhancement

#2842 Prevent duplicate loading of CSS files
  index.ejs
  webpack.common.ts
  webpack.prod.ts
Labels: bug, enhancement

#2876 Incorporate point search panel feedback
  src/app/components/Alerts/MoreResultsWhenLoggedIn.jsx
  src/app/components/Alerts/MoreResultsWhenLoggedIn.test.tsx
  src/app/components/Alerts/MoreResultsWhenLoggedIn.tsx
  src/app/components/Alerts/__snapshots__/MoreResultsWhenLoggedIn.test.tsx.snap
  src/app/components/DataCard/DataCard.jsx
  src/app/components/DataCard/DataList.jsx
  src/app/components/DataSelection/DataSelection.jsx
  src/app/components/PageFilterBox/PageFilterBox.jsx
  src/app/components/SearchFilter/utils.ts
  src/app/pages/MapPage/Components/DataSelectionResults.tsx
  src/app/pages/MapPage/Components/PointSearchResults.tsx
  src/app/pages/SearchPage/MapSearchResults/MapSearchResults.tsx
  src/app/pages/SearchPage/SearchPageResults.jsx
  src/app/pages/SearchPage/SearchResultsOverview.jsx
  src/app/utils/formatCount.test.ts
  src/app/utils/formatCount.ts
  src/map/services/map-search-results/map-search-results.js
  src/map/services/map-search/map-search.ts
  src/map/services/map-search/transform-result-by-type.js
  src/map/services/map-search/transform-result-by-type.test.js
  src/map/services/normalize/normalize.js
Labels: enhancement
