Repository Amsterdam/data-verkenner, pull requests merged in 2021-02, with the labels that each got.

#3954 Fix issue where loading state for CMS content was set incorrectly
  src/app/utils/useFromCMS.ts
Labels: bug

#3931 [DI2-146] Handle legacy drawing parameters for drawings
  src/app/pages/MapPage/MapContainer.tsx
  src/app/pages/MapPage/MapPanelContent.tsx
  src/app/pages/MapPage/draw/DrawResults.test.tsx
  src/app/pages/MapPage/draw/DrawResults.tsx
  src/app/pages/MapPage/draw/DrawTool.tsx
  src/app/pages/MapPage/query-params.test.ts
  src/app/pages/MapPage/query-params.ts
  src/app/utils/useParam.ts
Labels: enhancement

#3970 Add a test to verify the loading state of CMS content
  src/app/utils/useFromCMS.test.ts
Labels: enhancement

#3982 Remove html-loader from Webpack config
  package-lock.json
  package.json
  webpack.common.ts
Labels: dependencies

#3948 [DI2-188] Add a new section to the feedback modal to request new features
  src/app/components/Modal/FeedbackModal.jsx
Labels: enhancement

#3988 Chore increase coverage
  jest.config.js
  package.json
  src/app/components/DataSelection/DataSelectionDownloadButton.tsx
  src/app/components/PageFilterBox/PageFilterBox.jsx
  src/app/utils/isObject.test.ts
  src/app/utils/isObject.ts
  src/map/types/details.ts
  src/shared/services/data-selection/data-selection-api.js
  src/shared/services/geometry/geometry.test.ts
  src/shared/services/geometry/geometry.ts
  src/shared/services/is-defined.js
  src/shared/services/is-defined.test.js
  src/shared/services/is-object.js
  src/shared/services/is-object.test.js
  src/shared/services/search/search-formatter.js
Labels: enhancement

#4003 [DI2-274] Remove alert about missing content on article pages
  jest.config.js
  src/app/pages/ArticleDetailPage/ArticleDetailPage.jsx
Labels: enhancement

#4004 Update matomo tracker to the latest version
  package-lock.json
  package.json
Labels: dependencies

#3973 Move new map panel code from ARM to Atlas
  jest.config.js
  package-lock.json
  package.json
  src/app/pages/MapPage/components/Control/Control.tsx
  src/app/pages/MapPage/components/Control/index.ts
  src/app/pages/MapPage/components/DrawerOverlay/DrawerOverlay.test.tsx
  src/app/pages/MapPage/components/DrawerOverlay/DrawerOverlay.tsx
  src/app/pages/MapPage/components/DrawerOverlay/index.ts
  src/app/pages/MapPage/components/DrawerPanel/DrawerPanel.test.tsx
  src/app/pages/MapPage/components/DrawerPanel/DrawerPanel.tsx
  src/app/pages/MapPage/components/DrawerPanel/DrawerPanelHeader.test.tsx
  src/app/pages/MapPage/components/DrawerPanel/DrawerPanelHeader.tsx
  src/app/pages/MapPage/components/DrawerPanel/LargeDrawerPanel.test.tsx
  src/app/pages/MapPage/components/DrawerPanel/LargeDrawerPanel.tsx
  src/app/pages/MapPage/components/DrawerPanel/SmallDrawerPanel.test.tsx
  src/app/pages/MapPage/components/DrawerPanel/SmallDrawerPanel.tsx
  src/app/pages/MapPage/components/DrawerPanel/index.ts
  src/app/pages/MapPage/components/LegendControl/LegendControl.test.tsx
  src/app/pages/MapPage/components/LegendControl/LegendControl.tsx
  src/app/pages/MapPage/components/LegendControl/index.ts
  src/app/pages/MapPage/components/MapContainer/MapContainer.tsx
  src/app/pages/MapPage/components/MapContainer/index.ts
  src/app/pages/MapPage/components/MapOverlay/MapOverlay.tsx
  src/app/pages/MapPage/components/MapOverlay/index.ts
  src/app/pages/MapPage/components/ZoomControl/ZoomControl.test.tsx
  src/app/pages/MapPage/components/ZoomControl/ZoomControl.tsx
  src/app/pages/MapPage/components/ZoomControl/index.ts
  src/app/utils/useAnimationFrame.test.ts
  src/app/utils/useAnimationFrame.ts
  src/app/utils/useObserveSize.ts
Labels: enhancement

#3998 [DI2-146] Set initial drawings from url params
  src/app/pages/MapPage/components/MapContainer/MapContainer.test.tsx
  src/app/pages/MapPage/components/MapOverlay/MapOverlay.test.tsx
  src/app/pages/MapPage/draw/DrawTool.tsx
Labels: enhancement

#4007 [DI2-58] Add utility to enable feature toggles on a local machine
  docs/adr/003-keycloak-implementation.md
  docs/adr/004-feature-toggles.md
  docs/adr/README.md
  src/app/utils/isFeatureEnabled.test.ts
  src/app/utils/isFeatureEnabled.ts
Labels: enhancement

#4011 Remove type definitions for react-resize-detector
  package-lock.json
  package.json
  src/map/components/leaflet/MapLeaflet.jsx
Labels: dependencies, typescript

#4017 Update Amsterdam Styled Components to latest version
  package-lock.json
  package.json
  src/app/components/SearchFilter/filters/RadioFilter.tsx
Labels: dependencies, enhancement

#4018 Upgrade Amsterdam React Maps to latest version
  package-lock.json
  package.json
  src/app/components/IconButton/IconButton.jsx
  src/app/components/IconButton/__snapshots__/IconButton.test.jsx.snap
  src/app/components/PanoramaViewer/PanoramaViewerControls.tsx
  src/app/components/ToggleFullscreen/ToggleFullscreen.tsx
Labels: dependencies, enhancement
